//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SENDITEntities : DbContext
    {
        public SENDITEntities()
            : base("name=SENDITEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CUSTOMER> CUSTOMER { get; set; }
        public virtual DbSet<DELIVERY> DELIVERY { get; set; }
        public virtual DbSet<ORDER> ORDER { get; set; }
        public virtual DbSet<PACKAGE> PACKAGE { get; set; }
        public virtual DbSet<ROUTE> ROUTE { get; set; }
        public virtual DbSet<USER> USER { get; set; }
    }
}
