//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER
    {
        public int ID { get; set; }
        public Nullable<System.Guid> ORDER_NUMBER { get; set; }
        public Nullable<int> ORDER_STATUS { get; set; }
        public Nullable<int> BOXES_AMOUNT { get; set; }
        public Nullable<System.DateTime> DEADLINE_DATE { get; set; }
        public Nullable<int> CUSTOMER_ID { get; set; }
        public Nullable<int> ROUTE_ID { get; set; }
        public Nullable<int> ID_DELIVERY { get; set; }
        public Nullable<int> ID_USER { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual DELIVERY DELIVERY { get; set; }
        public virtual USER USER { get; set; }
        public virtual ROUTE ROUTE { get; set; }
    }
}
